Air: air::E_MinimizeMaximize Class Reference
air::E_MinimizeMaximize Class Reference
#include <E_MinimizeMaximize.hpp>
Public Member Functions
E_MinimizeMaximize (void)
~E_MinimizeMaximize (void)
Static Public Member Functions
static void XN_CALLBACK_TYPE onSwipeUp (XnFloat velocity, XnFloat angle, void *userCxt)
static void XN_CALLBACK_TYPE onSwipeDown (XnFloat velocity, XnFloat angle, void *userCxt)
Detailed Description
Event class. Associate up/down swipe gesture to the action of minimizing/maximizing the running application which has the focus. Inherit from XnVSwipeDetector, since it must detect swipe gestures.
Author:
Pierre Alletru
Definition at line 25 of file E_MinimizeMaximize.hpp.
Constructor & Destructor Documentation
E_MinimizeMaximize::E_MinimizeMaximize (void)
Default constructor.
Definition at line 10 of file E_MinimizeMaximize.cpp.
References MM_MIN_SPEED, onSwipeDown(), and onSwipeUp().
E_MinimizeMaximize::~E_MinimizeMaximize (void)
Destructor.
Definition at line 19 of file E_MinimizeMaximize.cpp.
Member Function Documentation
void XN_CALLBACK_TYPE E_MinimizeMaximize::onSwipeDown (XnFloat velocity, XnFloat angle, void * userCxt) [static]
OpenNI callback called when a swipe down gesture is recognized. Perform a keyboard event to minimize current application.
Parameters:
velocity Velocity of the swipe movement.
angle The angle of the movement, with respect to the Y axis (vertical).
userCxt A pointer to some user data. Required by OpenNI, but always NULL in this case.
Definition at line 40 of file E_MinimizeMaximize.cpp.
References air::os::IKeyboard::AltLeft, air::os::IKeyboard::Down, air::os::IKeyboard::F9, air::os::Keyboard::keyPress(), air::os::Keyboard::keyRelease(), and air::os::IKeyboard::SuperLeft.
Referenced by E_MinimizeMaximize().
void XN_CALLBACK_TYPE E_MinimizeMaximize::onSwipeUp (XnFloat velocity, XnFloat angle, void * userCxt) [static]
OpenNI callback called when a swipe up gesture is recognized. Perform a keyboard event to maximize current application.
Parameters:
velocity Velocity of the swipe movement.
angle The angle of the movement, with respect to the Y axis (vertical).
userCxt A pointer to some user data. Required by OpenNI, but always NULL in this case.
Definition at line 23 of file E_MinimizeMaximize.cpp.
References air::os::IKeyboard::AltLeft, air::os::IKeyboard::F10, air::os::Keyboard::keyPress(), air::os::Keyboard::keyRelease(), air::os::IKeyboard::SuperLeft, and air::os::IKeyboard::Up.
Referenced by E_MinimizeMaximize().
The documentation for this class was generated from the following files:
/home/dd/Desktop/Air/Air/include/E_MinimizeMaximize.hpp
/home/dd/Desktop/Air/Air/src/E_MinimizeMaximize.cpp