Air: air::E_KillCurrent Class Reference
air::E_KillCurrent Class Reference
#include <E_KillCurrent.hpp>
Public Member Functions
E_KillCurrent (void)
~E_KillCurrent (void)
Static Public Member Functions
static void XN_CALLBACK_TYPE onPush (XnFloat velocity, XnFloat angle, void *userCxt)
Detailed Description
Event class. Associate push gesture to the action of closing the running application which has the focus. Inherit from XnVPushDetector, since it must detect push gestures.
Author:
Pierre Alletru
Definition at line 25 of file E_KillCurrent.hpp.
Constructor & Destructor Documentation
E_KillCurrent::E_KillCurrent (void)
Default constructor.
Definition at line 10 of file E_KillCurrent.cpp.
References KC_MIN_SPEED, and onPush().
E_KillCurrent::~E_KillCurrent (void)
Destructor.
Definition at line 18 of file E_KillCurrent.cpp.
Member Function Documentation
void XN_CALLBACK_TYPE E_KillCurrent::onPush (XnFloat velocity, XnFloat angle, void * userCxt) [static]
OpenNI callback called when a push gesture is recognized. Perform an 'Alt + F4' keyboard event to kill current application.
Parameters:
velocity Velocity of the push movement.
angle The angle of the movement, with respect to the Z axis (depth).
userCxt A pointer to some user data. Required by OpenNI, but always NULL in this case.
Definition at line 22 of file E_KillCurrent.cpp.
References air::os::IKeyboard::AltLeft, air::os::IKeyboard::F4, air::os::Keyboard::keyPress(), and air::os::Keyboard::keyRelease().
Referenced by E_KillCurrent().
The documentation for this class was generated from the following files:
/home/dd/Desktop/Air/Air/include/E_KillCurrent.hpp
/home/dd/Desktop/Air/Air/src/E_KillCurrent.cpp