Air: air::OpenNIBox Class Reference
air::OpenNIBox Class Reference
#include <OpenNIBox.hpp>
Public Member Functions
void initialize (void)
void waitAndUpdate (void)
void stop (void)
xn::Context & getContext (void)
xn::DepthGenerator & getDepthGenerator (void)
xn::FingersGenerator & getFingersGenerator (void)
Detailed Description
Handle OpenNI operations and data.
Author:
Pierre Alletru
Definition at line 20 of file OpenNIBox.hpp.
Member Function Documentation
xn::Context & OpenNIBox::getContext (void)
Get the context.
Returns:
A reference to the OpenNI context object.
Definition at line 56 of file OpenNIBox.cpp.
Referenced by air::NITEBox::initialize(), and air::NITEBox::update().
xn::DepthGenerator & OpenNIBox::getDepthGenerator (void)
Get the depth generator.
Returns:
A reference to the OpenNI depth generator object.
Definition at line 61 of file OpenNIBox.cpp.
Referenced by air::Viewer::initialize(), air::CoordConverter::realWorldToNIScreen(), and air::CoordConverter::realWorldToScreenSize().
xn::FingersGenerator & OpenNIBox::getFingersGenerator (void)
Get the fingers generator.
Returns:
A reference to the FingersGenerator object.
Definition at line 66 of file OpenNIBox.cpp.
void OpenNIBox::initialize (void)
Initialize OpenNI framework.
Definition at line 8 of file OpenNIBox.cpp.
References CHECK_RS.
void OpenNIBox::stop (void)
Stop and clean OpenNI.
Definition at line 49 of file OpenNIBox.cpp.
void OpenNIBox::waitAndUpdate (void)
Run OpenNI,updating session for each frame.
Definition at line 41 of file OpenNIBox.cpp.
References CHECK_RS.
The documentation for this class was generated from the following files:
/home/dd/Desktop/Air/Air/include/OpenNIBox.hpp
/home/dd/Desktop/Air/Air/src/OpenNIBox.cpp