Air: air::E_MouseMove Class Reference
air::E_MouseMove Class Reference
#include <E_MouseMove.hpp>
Public Member Functions
E_MouseMove (void)
~E_MouseMove (void)
void OnPointCreate (const XnVHandPointContext *cxt)
void OnPointUpdate (const XnVHandPointContext *cxt)
void OnPointDestroy (XnUInt32 nID)
Detailed Description
Definition at line 20 of file E_MouseMove.hpp.
Constructor & Destructor Documentation
E_MouseMove::E_MouseMove (void)
Definition at line 29 of file E_MouseMove.cpp.
References air::os::Screen::getResX(), PX, and PY.
E_MouseMove::~E_MouseMove (void)
Definition at line 38 of file E_MouseMove.cpp.
Member Function Documentation
void E_MouseMove::OnPointCreate (const XnVHandPointContext * cxt)
Definition at line 42 of file E_MouseMove.cpp.
References g_openNI, and air::OpenNIBox::getDepthGenerator().
void E_MouseMove::OnPointDestroy (XnUInt32 nID)
Definition at line 88 of file E_MouseMove.cpp.
void E_MouseMove::OnPointUpdate (const XnVHandPointContext * cxt)
Definition at line 53 of file E_MouseMove.cpp.
References g_openNI, air::OpenNIBox::getDepthGenerator(), PX, PY, air::Viewer::setHandPosition(), air::os::Mouse::setPosition(), and SPEED_FACTOR.
The documentation for this class was generated from the following files:
/home/dd/Desktop/Air/include/E_MouseMove.hpp
/home/dd/Desktop/Air/src/E_MouseMove.cpp