Air: air::E_SwitchApp Class Reference
air::E_SwitchApp Class Reference
#include <E_SwitchApp.hpp>
Public Member Functions
E_SwitchApp (void)
~E_SwitchApp (void)
Static Public Member Functions
static void XN_CALLBACK_TYPE onSwipe (XnFloat velocity, XnFloat angle, void *userCxt)
Detailed Description
Event class. Associate left/right swipe gesture to the action of switching between the current running applications. Inherit from XnVSwipeDetector, since it must detect swipe gestures.
Author:
Pierre Alletru
Definition at line 25 of file E_SwitchApp.hpp.
Constructor & Destructor Documentation
E_SwitchApp::E_SwitchApp (void)
Default constructor.
Definition at line 10 of file E_SwitchApp.cpp.
References onSwipe(), and SA_MIN_SPEED.
E_SwitchApp::~E_SwitchApp (void)
Destructor.
Definition at line 19 of file E_SwitchApp.cpp.
Member Function Documentation
void XN_CALLBACK_TYPE E_SwitchApp::onSwipe (XnFloat velocity, XnFloat angle, void * userCxt) [static]
OpenNI callback called when a swipe left or swipe right gesture is recognized. Perform an 'Alt + Tab' keyboard event to switch current applications.
Parameters:
velocity Velocity of the swipe movement.
angle The angle of the movement, with respect to the X axis (horizontal).
userCxt A pointer to some user data. Required by OpenNI, but always NULL in this case.
Definition at line 23 of file E_SwitchApp.cpp.
References air::os::IKeyboard::AltLeft, air::os::Keyboard::keyPress(), air::os::Keyboard::keyRelease(), air::os::IKeyboard::ShiftLeft, and air::os::IKeyboard::Tab.
Referenced by E_SwitchApp().
The documentation for this class was generated from the following files:
/tmp/Air/Air/include/E_SwitchApp.hpp
/tmp/Air/Air/src/E_SwitchApp.cpp