Air: air::CoordConverter Class Reference
air::CoordConverter Class Reference
#include <CoordConverter.hpp>
Static Public Member Functions
static XnPoint3D realWorldToScreenSize (XnPoint3D point)
static XnPoint3D realWorldToNIScreen (XnPoint3D point)
static XnPoint3D screenSizeToSpeedFactor (XnPoint3D point, int speedFactor=DEFAULT_SPEED_FACTOR)
Detailed Description
Offer methods for coordinates conversion. Every methods are static.
Author:
Pierre Alletru
Definition at line 22 of file CoordConverter.hpp.
Member Function Documentation
XnPoint3D CoordConverter::realWorldToNIScreen (XnPoint3D point) [static]
Converts a point in real world coordinates to OpenNI screen coordinates (default is VGA).
Parameters:
point A given point.
Returns:
The point converted to OpenNI screen coordinates.
Definition at line 35 of file CoordConverter.cpp.
References g_openNI, and air::OpenNIBox::getDepthGenerator().
XnPoint3D CoordConverter::realWorldToScreenSize (XnPoint3D point) [static]
Converts a point in real world coordinates to a point on full screen coordinates.
Parameters:
point A given point.
Returns:
The point converted to screen coordinates.
Definition at line 18 of file CoordConverter.cpp.
References g_openNI, air::OpenNIBox::getDepthGenerator(), air::os::Screen::getResX(), and air::os::Screen::getResY().
XnPoint3D CoordConverter::screenSizeToSpeedFactor (XnPoint3D point, int speedFactor = DEFAULT_SPEED_FACTOR) [static]
Convert a point from full screen coordinates to a point at a higher distance to the center of the screen.
Parameters:
point A given point.
speedFactor Optional. A factor to increase the distance.
Returns:
The converted point.
Definition at line 48 of file CoordConverter.cpp.
References air::os::Screen::getResX(), air::os::Screen::getResY(), PX, and PY.
The documentation for this class was generated from the following files:
/home/dd/Desktop/Air/Air/include/CoordConverter.hpp
/home/dd/Desktop/Air/Air/src/CoordConverter.cpp