Air: air::os::Screen Class Reference
air::os::Screen Class Reference
#include <Screen.hpp>
Classes
struct Rectangle
Public Member Functions
Screen (void)
~Screen (void)
int getResX (void)
int getResY (void)
void drawRectangle (int x, int y, int sizeX, int sizeY, const air::Color &color)
void clear (void)
void display (void)
Screen (void)
~Screen (void)
int getResX (void)
int getResY (void)
void drawRectangle (int x, int y, int sizeX, int sizeY, const air::Color &color)
void clear (void)
void display (void)
Detailed Description
Implementation of IScreen for unix systems. Offers methods related to the OS screen.
The class is threaded to be able to draw above screen. SFML library is used for thread managment (see http://www.sfml-dev.org/).
Author:
Pierre Alletru
Implementation of IScreen for Windows. Offers methods related to the OS screen.
The class is threaded to be able to draw above screen. SFML library is used for thread managment (see http://www.sfml-dev.org/).
Author:
Pierre Alletru
Definition at line 35 of file Screen.hpp.
Constructor & Destructor Documentation
Screen::Screen (void)
Default constructor.
Definition at line 7 of file Screen.cpp.
Screen::~Screen (void)
Destructor.
Definition at line 16 of file Screen.cpp.
air::os::Screen::Screen (void)
Default constructor.
air::os::Screen::~Screen (void)
Destructor.
Member Function Documentation
void Screen::clear (void) [virtual]
Clear the previsouly drawn shapes. So restore screen.
Implements air::os::IScreen.
Definition at line 51 of file Screen.cpp.
Referenced by air::FingersListener::FingersUpdate().
void air::os::Screen::clear (void) [virtual]
Clear the previsouly drawn shapes. So restore screen.
Implements air::os::IScreen.
void Screen::display (void) [virtual]
Actually draw the shapes to the screen.
Implements air::os::IScreen.
Definition at line 90 of file Screen.cpp.
Referenced by air::FingersListener::FingersUpdate().
void air::os::Screen::display (void) [virtual]
Actually draw the shapes to the screen.
Implements air::os::IScreen.
void Screen::drawRectangle (int x, int y, int sizeX, int sizeY, const air::Color & color) [virtual]
Draw a filled rectangle on screen.
Parameters:
x The x position of the top left corner of the rectangle.
x The y position of the top left corner of the rectangle.
sizeX The width of the rectangle.
sizeY The height of the rectangle.
color The color of the rectangle.
Implements air::os::IScreen.
Definition at line 67 of file Screen.cpp.
void air::os::Screen::drawRectangle (int x, int y, int sizeX, int sizeY, const air::Color & color) [virtual]
Draw a filled rectangle on screen.
Parameters:
x The x position of the top left corner of the rectangle.
x The y position of the top left corner of the rectangle.
sizeX The width of the rectangle.
sizeY The height of the rectangle.
color The color of the rectangle.
Implements air::os::IScreen.
int air::os::Screen::getResX (void) [virtual]
Get the x resolution of the screen.
Returns:
The x resolution of the screen.
Implements air::os::IScreen.
int Screen::getResX (void) [virtual]
Get the x resolution of the screen.
Returns:
The x resolution of the screen.
Implements air::os::IScreen.
Definition at line 25 of file Screen.cpp.
Referenced by air::Viewer::initialize(), air::CoordConverter::realWorldToScreenSize(), and air::CoordConverter::screenSizeToSpeedFactor().
int Screen::getResY (void) [virtual]
Get the y resolution of the screen.
Returns:
The y resolution of the screen.
Implements air::os::IScreen.
Definition at line 38 of file Screen.cpp.
Referenced by air::CoordConverter::realWorldToScreenSize(), and air::CoordConverter::screenSizeToSpeedFactor().
int air::os::Screen::getResY (void) [virtual]
Get the y resolution of the screen.
Returns:
The y resolution of the screen.
Implements air::os::IScreen.
The documentation for this class was generated from the following files:
/home/dd/Desktop/Air/Air/include/OS/unix/Screen.hpp
/home/dd/Desktop/Air/Air/include/OS/win32/Screen.hpp
/home/dd/Desktop/Air/Air/src/OS/unix/Screen.cpp
/home/dd/Desktop/Air/Air/src/OS/win32/Screen.cpp