Air: air::FingersListener Class Reference
air::FingersListener Class Reference
#include <FingersListener.hpp>
Static Public Member Functions
static void XN_CALLBACK_TYPE FingersCreate (xn::FingersGenerator &gen, XnUserID id, xn::FingersData *fingersData, XnFloat time, void *userData)
static void XN_CALLBACK_TYPE FingersUpdate (xn::FingersGenerator &gen, XnUserID id, xn::FingersData *fingersData, XnFloat time, void *userData)
static void XN_CALLBACK_TYPE FingersDestroy (xn::FingersGenerator &gen, XnUserID id, XnFloat time, void *userData)
Detailed Description
Handle the fingers related callbacks, which are called by xn::FingersGenerator. Transmitt fingers data to a MouseControl object, since fingers are controlling mouse. If no mouse action is recognized, simply display fingers positions above screen.
Author:
Pierre Alletru
Definition at line 23 of file FingersListener.hpp.
Member Function Documentation
void XN_CALLBACK_TYPE FingersListener::FingersCreate (xn::FingersGenerator & gen, XnUserID id, xn::FingersData * fingersData, XnFloat time, void * userData) [static]
xn::FingersGenerator callback called when a hand and its fingers has been detected for the first time in the session. Does no action.
Parameters:
gen A reference to the FingersGenerator object which has detected the hand and generated the given data.
id The hand id.
fingersData A pointer to a structure containing hand and fingers information.
time A timestamp, in seconds.
userData A pointer to some undefined data. Not used here (is equal to NULL).
Definition at line 78 of file FingersListener.cpp.
void XN_CALLBACK_TYPE FingersListener::FingersDestroy (xn::FingersGenerator & gen, XnUserID id, XnFloat time, void * userData) [static]
xn::FingersGenerator callback called when a hand is lost (is no longer detected).
Parameters:
gen A reference to the FingersGenerator object which has pereviously detected the hand.
id The hand id.
time A timestamp, in seconds.
userData A pointer to some undefined data. Not used here (is equal to NULL).
Definition at line 86 of file FingersListener.cpp.
void XN_CALLBACK_TYPE FingersListener::FingersUpdate (xn::FingersGenerator & gen, XnUserID id, xn::FingersData * fingersData, XnFloat time, void * userData) [static]
xn::FingersGenerator callback called every frame while a hand and its fingers are still detected, indicating hand and fingers positions and related information. Essentially transmitt data to the MouseControl object member, and draw fingers on OS screen if MouseControl doesn't recognize any fingers gesture.
Parameters:
gen A reference to the FingersGenerator object which has detected the hand and generated the given data.
id The hand id.
fingersData A pointer to a structure containing hand and fingers information.
time A timestamp, in seconds.
userData A pointer to some undefined data. Not used here (is equal to NULL).
Definition at line 56 of file FingersListener.cpp.
References air::os::Screen::clear(), air::os::Screen::display(), and air::MouseControl::update().
The documentation for this class was generated from the following files:
/home/dd/Desktop/Air/Air/include/FingersListener.hpp
/home/dd/Desktop/Air/Air/src/FingersListener.cpp