Air: xn::math Namespace Reference
xn::math Namespace Reference
Functions
Point2Df PointsCenter (Point2Df a, Point2Df b)
Point3Df PointsCenter (Point3Df a, Point3Df b)
bool Equal (Point2Df a, Point2Df b)
bool Equal (Point3Df a, Point3Df b)
Vector2Df PointsVector (Point2Df a, Point2Df b)
Vector3Df PointsVector (Point3Df a, Point3Df b)
float PointsDistance (Point2Df a, Point2Df b)
float PointsDistance (Point3Df a, Point3Df b)
float VectorsDotProduct (Vector2Df a, Vector2Df b)
float VectorsDotProduct (Vector3Df a, Vector3Df b)
Vector3Df VectorsCrossProduct (Vector3Df a, Vector3Df b)
float VectorMagnitude (Vector2Df v)
float VectorMagnitude (Vector3Df v)
float VectorsAngle (Vector2Df a, Vector2Df b)
float VectorsAngle (Vector3Df a, Vector3Df b)
Point2Df PointRotate (Point2Df p, float angle, Point2Df centerOfRot)
Point3Df PointsCenterOfMass (const list< Point3Df > &points)
template<typename T >
float PointsClosest2D_BruteForce (typename list< T >::iterator begin, typename list< T >::iterator end, const T &point, typename list< T >::iterator &closest)
Function Documentation
bool xn::math::Equal (Point2Df a, Point2Df b)
Check wheter or not two 2D points are equals (means have identical coordinates).
Parameters:
a A point.
b Another point.
Returns:
true if a and b are equals, false otherwise.
Definition at line 37 of file Math.cpp.
References xn::Point2Df::X, and xn::Point2Df::Y.
bool xn::math::Equal (Point3Df a, Point3Df b)
Check wheter or not two 3D points are equals (means have identical coordinates).
Parameters:
a A point.
b Another point.
Returns:
true if a and b are equals, false otherwise.
Definition at line 42 of file Math.cpp.
References xn::Point2Df::X, xn::Point2Df::Y, and xn::Point3Df::Z.
Point2Df xn::math::PointRotate (Point2Df p, float angle, Point2Df centerOfRot)
Rotates a 2D point around another point.
Parameters:
p The point to rotate.
angle The angle of rotation, in degrees.
centerOfRot The point around which to rotate p.
Returns:
'p' rotated of 'angle' degrees around point 'centerOfRot'.
Definition at line 143 of file Math.cpp.
References DEGREES_TO_RADIAN, xn::Point2Df::X, and xn::Point2Df::Y.
Point3Df xn::math::PointsCenter (Point3Df a, Point3Df b)
Find the center of two 3D points.
Parameters:
a A point.
b Another point.
Returns:
A point at the center of a and b.
Definition at line 26 of file Math.cpp.
References xn::Point2Df::X, xn::Point2Df::Y, and xn::Point3Df::Z.
Point2Df xn::math::PointsCenter (Point2Df a, Point2Df b)
Find the center of two 2D points.
Parameters:
a A point.
b Another point.
Returns:
A point at the center of a and b.
Definition at line 16 of file Math.cpp.
References xn::Point2Df::X, and xn::Point2Df::Y.
Point3Df xn::math::PointsCenterOfMass (const list< Point3Df > & points)
Computes the center of mass of a 3D points.
Parameters:
points A list of points.
Returns:
The center of mass of the given points.
Definition at line 168 of file Math.cpp.
References xn::Point2Df::X.
template<typename T > float xn::math::PointsClosest2D_BruteForce (typename list< T >::iterator begin, typename list< T >::iterator end, const T & point, typename list< T >::iterator & closest)
Find the closest point to a given 2D point, using basic bruteforce algorithm (exhaustive research).
Template function. Can use different types of points structure (e.g Point2Df, Point3Df, etc).
Parameters:
begin An iterator from a list of points, used to start research.
end An iterator from a list of points, used as an end point to stop researching.
point The reference point used for the closest point research.
closest A reference to an iterator of the type of the research list. This iterator will be set to the position of the closest point.
Returns:
The distance between the given point and the closest point found.
Definition at line 29 of file XnMathTemplates.hpp.
References PointsDistance().
float xn::math::PointsDistance (Point3Df a, Point3Df b)
Computes the distance of two 3D points.
Parameters:
a A point.
b Another point.
Returns:
The distance between a and b.
Definition at line 77 of file Math.cpp.
References xn::Point2Df::X, xn::Point2Df::Y, and xn::Point3Df::Z.
float xn::math::PointsDistance (Point2Df a, Point2Df b)
Computes the distance of two 2D points.
Parameters:
a A point.
b Another point.
Returns:
The distance between a and b.
Definition at line 69 of file Math.cpp.
References xn::Point2Df::X, and xn::Point2Df::Y.
Referenced by PointsClosest2D_BruteForce().
Vector2Df xn::math::PointsVector (Point2Df a, Point2Df b)
Creates a 2D vector from point a to point b.
Parameters:
a A point.
b Another point.
Returns:
A 2D vector from a to b.
Definition at line 47 of file Math.cpp.
References xn::Point2Df::X, and xn::Point2Df::Y.
Vector3Df xn::math::PointsVector (Point3Df a, Point3Df b)
Creates a 3D vector from point a to point b.
Parameters:
a A point.
b Another point.
Returns:
A 3D vector from a to b.
Definition at line 57 of file Math.cpp.
References xn::Point2Df::X, xn::Point2Df::Y, and xn::Point3Df::Z.
float xn::math::VectorMagnitude (Vector3Df v)
Computes the magnitude of a 3D vector.
Parameters:
v A vector.
Returns:
The magnitude of v.
Definition at line 112 of file Math.cpp.
References xn::Point2Df::X, xn::Point2Df::Y, and xn::Point3Df::Z.
float xn::math::VectorMagnitude (Vector2Df v)
Computes the magnitude of a 2D vector.
Parameters:
v A vector.
Returns:
The magnitude of v.
Definition at line 107 of file Math.cpp.
References xn::Point2Df::X, and xn::Point2Df::Y.
Referenced by VectorsAngle().
float xn::math::VectorsAngle (Vector2Df a, Vector2Df b)
Find the angle between two 2D vectors.
Parameters:
a A vector.
b Another vector.
Returns:
The angle between a and b.
Definition at line 117 of file Math.cpp.
References RADIAN_TO_DEGREES, VectorMagnitude(), and VectorsDotProduct().
float xn::math::VectorsAngle (Vector3Df a, Vector3Df b)
Find the angle between two 3D vectors.
Parameters:
a A vector.
b Another vector.
Returns:
The angle between a and b.
Definition at line 130 of file Math.cpp.
References RADIAN_TO_DEGREES, VectorMagnitude(), and VectorsDotProduct().
Vector3Df xn::math::VectorsCrossProduct (Vector3Df a, Vector3Df b)
Computes the cross product of two 3D vectors.
Parameters:
a A vector.
b Another vector.
Returns:
The cross product of a and b.
Definition at line 96 of file Math.cpp.
References xn::Point2Df::X, xn::Point2Df::Y, and xn::Point3Df::Z.
float xn::math::VectorsDotProduct (Vector3Df a, Vector3Df b)
Computes the dot product of two 3D vectors.
Parameters:
a A vector.
b Another vector.
Returns:
The dot product of a and b.
Definition at line 91 of file Math.cpp.
References xn::Point2Df::X, xn::Point2Df::Y, and xn::Point3Df::Z.
float xn::math::VectorsDotProduct (Vector2Df a, Vector2Df b)
Computes the dot product of two 2D vectors.
Parameters:
a A vector.
b Another vector.
Returns:
The dot product of a and b.
Definition at line 86 of file Math.cpp.
References xn::Point2Df::X, and xn::Point2Df::Y.
Referenced by VectorsAngle().